### ISSUE TITLE
是否考虑支持完整链接搜索

### ISSUE THREAD

**Issue by poooooom** [huangbaihua001/RestfulToolkitX#111]
大佬，你好，是否考虑支持完整链接的API查询。
完整链接搜Controller时需要多做一步操作，去除请求头、域名和"?"之后的参数等才能搜索到。
例如：
接口完整地址为：http://xxx.com/api/project/detail?id=666&lt=xxxxxxxx
实际"http://xxx.com" 和 “?id=666&lt=xxxxxxxx” 对搜索都是没有用的数据，只有 “/api/project/detail” 可以搜索到对应的Controller。

可能我接触的链接种类少，不知道这个需求是不是个例，对其他人会不会有影响。

**Comment by huangbaihua001** [comment]
不支持哦~
