### ISSUE TITLE
json里面中文接收乱码，要加个请求头设置编码

### ISSUE THREAD

**Issue by zundaren** [huangbaihua001/RestfulToolkitX#27]
![image](https://user-images.githubusercontent.com/44863479/165668302-8506bb00-c5e3-473b-9045-596e085edbf3.png)
![image](https://user-images.githubusercontent.com/44863479/165668328-2e2169a8-b9d1-4581-84e5-c4317fb17d5d.png)

**Comment by huangbaihua001** [comment]
请进一步提供一下插件版本信息~
最新版，本地参照截图试图重现这个错误，并没有重现~ 
![微信截图_20220507211145](https://user-images.githubusercontent.com/314982/167255932-68626d7b-7639-43e8-b359-cdfb80df3943.png)

**Comment by zundaren** [comment]
![image](https://user-images.githubusercontent.com/44863479/167256072-1ccfdf84-016e-4f9f-9292-6b608d9131e3.png)
我用postman发送编码是正常的，这个是不是和idea的file encoing设置有关啊

**Comment by zundaren** [comment]
![image](https://user-images.githubusercontent.com/44863479/167256123-55d6d6fe-fa4a-4b23-9326-85fa7f132d61.png)

**Comment by Matthew2Qiao** [comment]
执行插入和修改语句的时候传中文，数据库里面会显示为问号，用其他的插件接口测试不会出现这种情况，查询我的是可以正常显示中文的
