### ISSUE TITLE
有些小问题

### ISSUE THREAD

**Issue by hl976440572** [huangbaihua001/RestfulToolkitX#3]
![image](https://user-images.githubusercontent.com/29592294/149725976-c692e3a2-0d60-41ba-8e51-8985c0329488.png)
会多出并不存在的接口
![image](https://user-images.githubusercontent.com/29592294/149726136-1eb69a61-da36-405e-9ddf-8382ee6f8356.png)
请求返回体中的中文变成了乱码

**Comment by huangbaihua001** [comment]
请问多出来的接口是在测试Controller时 @RequestMapping 注解的么？
